Handle connection-level errors correctly on agents
spdy-http2/node-spdy pull request #295
Opened 2016-11-07 23:36 UTC by anandsuresh

The old code was missing a handler for the connection-level "error"
events. This commit adds an error-handler that:
- destroys the connection socket
- re-emits the "error" on the agent that user-code can handle as needed

2017-01-29 22:52 UTC, diasdavid commented
Hi @anandsuresh, seems you have been waiting on this one for a bit. [I'm going to be maintaining](https://github.com/indutny/spdy-transport/issues/37#issuecomment-275813942_ node-spdy and spdy-transport from now on and I hope I can get up to spdy in all the details soon enough. Until then, this PR looks good to me, but could you add a test for when an error happens, so that we are sure the propagation is correct and avoid regressions in the future? Thanks!

2017-01-29 22:52 UTC, daviddias requested changes
Hi @anandsuresh, seems you have been waiting on this one for a bit. I'm going to be[ maintaining](https://github.com/indutny/spdy-transport/issues/37#issuecomment-275813942_) node-spdy and spdy-transport from now on and I hope I can get up to spdy in all the details soon enough. Until then, this PR looks good to me, but could you add a test for when an error happens, so that we are sure the propagation is correct and avoid regressions in the future? Thanks!

2017-02-01 20:21 UTC, anandsuresh commented
Whoops... missed this message @diasdavid. Will update the PR and ping back.

2017-05-23 01:17 UTC, diasdavid commented
@anandsuresh any update ?

2022-06-29 17:18 UTC, closed without merging